package dd254

import (
	"errors"
	"time"

	"github.com/google/uuid"
)

var (
	ErrNotFound        = errors.New("dd254 not found")
	ErrInvalidMarkings = errors.New("dd254 markings must be 'unclassified' (CMMC L1 boundary)")
	ErrInvalidClass    = errors.New("invalid classification_max")
	ErrUserNotInTenant = errors.New("user does not belong to this tenant")
)

// Markings outside this set are refused at the handler layer. The DB CHECK is
// the second line of defense.
const RequiredMarkings = "unclassified"

// Valid clearance_max values (must match the clearance_level enum).
var classifications = map[string]struct{}{
	"none":         {},
	"confidential": {},
	"secret":       {},
	"top_secret":   {},
	"ts_sci":       {},
}

func ValidClassification(s string) bool {
	_, ok := classifications[s]
	return ok
}

// Form is the metadata row for a DD254 document.
type Form struct {
	ID                uuid.UUID  `json:"id"`
	TenantID          uuid.UUID  `json:"tenant_id"`
	SubOrgID          *uuid.UUID `json:"sub_org_id,omitempty"`
	SubOrgName        *string    `json:"sub_org_name,omitempty"`
	ContractNumber    string     `json:"contract_number"`
	PrimeContractor   string     `json:"prime_contractor"`
	ClassificationMax string     `json:"classification_max"`
	PeriodStart       *time.Time `json:"period_start,omitempty"`
	PeriodEnd         *time.Time `json:"period_end,omitempty"`
	StorageKey        string     `json:"-"`
	Filename          string     `json:"filename"`
	ContentType       string     `json:"content_type"`
	SizeBytes         int64      `json:"size_bytes"`
	Markings          string     `json:"markings"`
	Status            string     `json:"status"`
	SupersedesID      *uuid.UUID `json:"supersedes_id,omitempty"`
	UploadedBy        uuid.UUID  `json:"uploaded_by"`
	UploadedByName    string     `json:"uploaded_by_name"`
	ReadOnCount       int        `json:"read_on_count"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
}

// AccessGrant is one entry in dd254_user_access, decorated with the user's display info.
type AccessGrant struct {
	UserID      uuid.UUID  `json:"user_id"`
	Name        string     `json:"name"`
	Email       string     `json:"email"`
	BriefedAt   *time.Time `json:"briefed_at,omitempty"`
	DebriefedAt *time.Time `json:"debriefed_at,omitempty"`
	AddedBy     uuid.UUID  `json:"added_by"`
	AddedAt     time.Time  `json:"added_at"`
}

// Detail bundles a form with its current read-on list.
type Detail struct {
	Form
	AccessGrants []AccessGrant `json:"access_grants"`
}

// CreateParams is the payload used by the handler to persist an uploaded form.
type CreateParams struct {
	ID                uuid.UUID // pre-generated by handler so storage_key embeds it
	TenantID          uuid.UUID
	SubOrgID          *uuid.UUID
	ContractNumber    string
	PrimeContractor   string
	ClassificationMax string
	PeriodStart       *time.Time
	PeriodEnd         *time.Time
	StorageKey        string
	Filename          string
	ContentType       string
	SizeBytes         int64
	Markings          string
	UploadedBy        uuid.UUID
	SupersedesID      *uuid.UUID
}

// ListFilters constrains a DD254 list query.
type ListFilters struct {
	TenantID    uuid.UUID
	SubOrgScope *uuid.UUID
	SubOrgID    *uuid.UUID
	Status      string
	Class       string
	Search      string
}

// SummaryStats for the DD254 page header tiles.
type SummaryStats struct {
	Active       int `json:"active"`
	ExpiringSoon int `json:"expiring_soon"`
	Expired      int `json:"expired"`
	NoReadOn     int `json:"no_read_on"`
}

// GrantAccessParams payload for adding a user to a DD254.
type GrantAccessParams struct {
	UserID      uuid.UUID `json:"user_id"`
	BriefedAt   *string   `json:"briefed_at,omitempty"`
	DebriefedAt *string   `json:"debriefed_at,omitempty"`
}

// Suggestion is what the visit-review screen receives to surface a recommended DD254.
type Suggestion struct {
	Form
	MatchReason string `json:"match_reason"` // "exact_class", "above_class", or "no_match"
}

// Authorization is a lightweight view of one DD254 the current user is
// read-on to. Returned from the IC-facing "what DD254s am I authorized
// under" lookup that powers the visit-submit wizard's contract picker.
type Authorization struct {
	ID                uuid.UUID  `json:"id"`
	ContractNumber    string     `json:"contract_number"`
	PrimeContractor   string     `json:"prime_contractor"`
	ClassificationMax string     `json:"classification_max"`
	PeriodStart       *time.Time `json:"period_start,omitempty"`
	PeriodEnd         *time.Time `json:"period_end,omitempty"`
}
