terraform {
  required_version = ">= 1.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
}

locals {
  domain             = var.environment == "prod" ? "app.${var.base_domain}" : "app-${var.environment}.${var.base_domain}"
  canonical_url      = var.public_domain != "" ? "https://${var.public_domain}" : "https://${local.domain}"
  upload_bucket_name = "fastfso-${var.environment}-uploads"
}

data "terraform_remote_state" "global" {
  backend = "gcs"

  config = {
    bucket = "tfstate-fastfso-com"
    prefix = "environments/global"
  }
}

module "services" {
  source = "../../modules/services"

  project_id = var.project_id
}

module "networking" {
  source = "../../modules/networking"

  project_id  = var.project_id
  region      = var.region
  environment = var.environment

  depends_on = [module.services]
}

module "database" {
  source = "../../modules/database"

  project_id  = var.project_id
  region      = var.region
  environment = var.environment
  network_id  = module.networking.network_id
  db_tier     = var.db_tier

  # Staging is torn down between releases to avoid paying for an idle
  # environment, so destroy must not be blocked. Staging data is disposable:
  # re-applying runs migrate + seed from scratch. Prod keeps the default (on).
  deletion_protection = false
}

module "compute" {
  source = "../../modules/compute"

  project_id                 = var.project_id
  region                     = var.region
  environment                = var.environment
  network_id                 = module.networking.network_id
  subnet_id                  = module.networking.subnet_id
  container_image            = var.container_image
  db_private_ip              = module.database.private_ip
  db_name                    = module.database.db_name
  db_user                    = module.database.db_user
  db_password_secret_id      = module.database.db_password_secret_id
  sendgrid_api_key_secret_id = data.terraform_remote_state.global.outputs.sendgrid_api_key_secret_id
  storage_bucket             = local.upload_bucket_name
  frontend_url               = local.canonical_url
  backend_url                = local.canonical_url
  task_log_sampling_ratio    = 0.1

  # Cloud Run v2 services and jobs default deletion_protection to true in the
  # provider. Staging is torn down between releases, so disable it here; prod
  # keeps the default.
  deletion_protection = false

  depends_on = [module.services]
}

module "storage" {
  source = "../../modules/storage"

  project_id                    = var.project_id
  environment                   = var.environment
  location                      = var.region
  backend_service_account_email = module.compute.service_account_email

  # Staging is torn down between releases and its uploads are disposable test
  # fixtures. Without this, `terraform destroy` deletes ~70 resources and then
  # fails on the non-empty bucket, stranding staging half-destroyed.
  force_destroy = true

  depends_on = [module.compute]
}

module "frontend" {
  source = "../../modules/frontend"

  project_id                 = var.project_id
  environment                = var.environment
  domain                     = local.domain
  public_access_tag_value_id = data.terraform_remote_state.global.outputs.public_access_tag_value_id

  # Built assets, regenerated by the deploy pipeline. Same reason as storage:
  # a non-empty bucket blocks the teardown.
  force_destroy = true

  depends_on = [module.services]
}

module "load_balancer" {
  source = "../../modules/load-balancer"

  project_id              = var.project_id
  environment             = var.environment
  domain                  = local.domain
  additional_domains      = var.public_domain != "" ? [var.public_domain] : []
  redirect_to             = var.public_domain
  neg_id                  = module.compute.neg_id
  frontend_bucket_name    = module.frontend.bucket_name
  certificate_map_id      = data.terraform_remote_state.global.outputs.certificate_map_id
  backend_log_sample_rate = 0.1
}

module "dns" {
  source = "../../modules/dns"

  project_id       = var.project_id
  dns_zone_name    = data.terraform_remote_state.global.outputs.dns_zone_name
  domain           = local.domain
  lb_static_ip     = module.load_balancer.static_ip
  create_www_cname = false

  depends_on = [module.services]
}
